"use client";
import Link from "next/link";
import type { ReactNode } from "react";
import { usePathname, useRouter } from "next/navigation";
import { useEffect } from "react";
import { ArrowLeft, Bell, Bookmark, Gavel, KeyRound, LogOut, MessageCircle, ShieldCheck, UserRound } from "lucide-react";
import { BrandLogo } from "@/shared/components/brand-logo";
import { signOut, useSession } from "@real-estate/auth/client";
const items=[["Profile",UserRound,"/account/profile"],["Security",ShieldCheck,"/account/security"],["Sessions",KeyRound,"/account/sessions"],["Saved",Bookmark,"/account/saved"],["My bids",Gavel,"/account/bids"],["Messages",MessageCircle,"/account/messages"],["Alerts",Bell,"/account/alerts"]] as const;
export function AccountShell({children,title,description}:{children:ReactNode;title:string;description:string}){const path=usePathname();const router=useRouter();const session=useSession();useEffect(()=>{if(!session.isPending&&!session.data)router.replace(`/sign-in?callbackURL=${encodeURIComponent(path)}`)},[path,router,session.data,session.isPending]);if(session.isPending||!session.data)return <div className="grid min-h-screen place-items-center text-sm text-slate-500">Checking your session…</div>;return <div className="min-h-screen bg-slate-50"><header className="border-b bg-white"><div className="mx-auto flex max-w-7xl items-center justify-between px-5 py-4"><BrandLogo compact /><Link href="/" className="flex items-center gap-2 text-sm font-semibold text-slate-600"><ArrowLeft className="size-4" />Back to marketplace</Link></div></header><div className="mx-auto grid max-w-7xl gap-7 px-5 py-8 lg:grid-cols-[240px_1fr]"><aside className="surface h-fit rounded-2xl p-3"><nav className="space-y-1">{items.map(([label,Icon,href])=><Link key={href} href={href} className={`flex items-center gap-3 rounded-xl px-3 py-3 text-sm font-medium ${path===href?"bg-emerald-50 text-emerald-900":"text-slate-600 hover:bg-slate-50"}`}><Icon className="size-4" />{label}</Link>)}</nav><button onClick={()=>signOut({fetchOptions:{onSuccess:()=>location.assign("/")}})} className="mt-3 flex w-full items-center gap-3 border-t px-3 pt-4 text-sm font-medium text-red-600"><LogOut className="size-4" />Sign out</button></aside><main><div className="mb-6"><h1 className="text-3xl font-bold tracking-tight">{title}</h1><p className="mt-2 text-sm text-slate-500">{description}</p></div>{children}</main></div></div>}
